library(class)
library(e1071)
features = read.csv("/home/mischka/projects/school/applied-computing/cleaned.csv")
model <- naiveBayes(features[,colnames(features)!="sentiment"], features[,colnames(features)=="sentiment"])
result <- predict(model, features[,colnames(features)!="sentiment"])
table(result, features[,colnames(features)=="sentiment"])
